### ISSUE TITLE
Having issues with step 6 (Snap origins and destinations of all trips to OSM)

### ISSUE THREAD

**Issue by Mohammadabd** [misteroda/movi#2]
I have been trying to run the simulation but stuck at step 6 where osrm is needed to work with sim image. It seems that response from osrm is null. I've checked the volumes of osrm data in docker-compose.yml (NewYork.osrm) and it seems that it is fine:
`./osrm:/data` but not sure why osrm returns null for requests from `snap_to_road.py`. Here is the log:

```
docker-compose run sim python src/preprocessing/snap_to_road.py ./data/trip_records/trips_2016-05.csv ./data/trip_records/mm_trips_2016-05.csv

Starting fleet-sim_osrm_1 ... done
/usr/local/lib/python3.6/site-packages/numpy/lib/arraysetops.py:580: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
  mask |= (ar1 == a)
load 12864494 rows
n: 0
Traceback (most recent call last):
  File "src/preprocessing/snap_to_road.py", line 33, in <module>
    df = create_snapped_trips(df, engine)
  File "src/preprocessing/snap_to_road.py", line 16, in create_snapped_trips
    mm_origins += [loc for loc, _ in engine.nearest_road(origins)]
  File "/home/src/preprocessing/../simulator/services/osrm_engine.py", line 18, in nearest_road
    responses = self.async_requester.send_async_requests(urllist)
  File "/home/src/preprocessing/../simulator/services/async_requester.py", line 21, in send_async_requests
    responses = list(self.executor.map(self.get_batch, batch_urllist))
  File "/usr/local/lib/python3.6/concurrent/futures/_base.py", line 586, in result_iterator
    yield fs.pop().result()
  File "/usr/local/lib/python3.6/concurrent/futures/_base.py", line 432, in result
    return self.__get_result()
  File "/usr/local/lib/python3.6/concurrent/futures/_base.py", line 384, in __get_result
    raise self._exception
  File "/usr/local/lib/python3.6/concurrent/futures/thread.py", line 56, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/home/src/preprocessing/../simulator/services/async_requester.py", line 31, in get_batch
    return [self.get_json(url) for url in urllist]
  File "/home/src/preprocessing/../simulator/services/async_requester.py", line 31, in <listcomp>
    return [self.get_json(url) for url in urllist]
  File "/home/src/preprocessing/../simulator/services/async_requester.py", line 26, in get_json
    result = requests.get(url).json()
  File "/usr/local/lib/python3.6/site-packages/requests/models.py", line 896, in json
    return complexjson.loads(self.text, **kwargs)
  File "/usr/local/lib/python3.6/json/__init__.py", line 354, in loads
    return _default_decoder.decode(s)
  File "/usr/local/lib/python3.6/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/local/lib/python3.6/json/decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

![image](https://user-images.githubusercontent.com/23286517/96072730-ea021e00-0e72-11eb-9d66-a906695b1315.png)

P.S: issue is becausse of adding proxy in dockerfile

**Comment by Xiaobing-Shen** [comment]
Hi, 
I have the same issue, do you know how to fix it ?

**Comment by Mohammadabd** [comment]
> Hi,
> I have the same issue, do you know how to fix it ?

Are you adding proxy to your Dockerfile? I was not able to get it run with proxy. So I just switched to another computer that does not have firewall and ran it successfully. However getting error in `create_tt_map` as it does not find any route for the lat and lons that are generated from the grid.

**Comment by Xiaobing-Shen** [comment]
Yeah, I also fixed that. And I have the same issue for “create_tt_map.py" and I just skip those items which cannot find any route. It seems we can fix this issue by add some parameter like “continue_straight” to osrm to allow U-turn but I did not try that. 

But then the new issue appears when I run “run.py”. it seems we do not have any model file for “ dispatch_policy.build_q_network(load_network=FLAGS.load_network)” to load and then result in error.

**Comment by Mohammadabd** [comment]
> Yeah, I also fixed that. And I have the same issue for “create_tt_map.py" and I just skip those items which cannot find any route. It seems we can fix this issue by add some parameter like “continue_straight” to osrm to allow U-turn but I did not try that. But then the new issue appears when I run “run.py”. it seems we do not have any model file for “ dispatch_policy.build_q_network(load_network=FLAGS.load_network)” to load and then result in error.
> […](#)

`FLAGS.load_network` is set to False by default. So it trains a network and saves into `logs/{FLAGS.tag}/networks`. Then later on if you wanted to load the existing network, you can set that flag to True.

**Comment by kingchiuoy** [comment]
Hi,
Have you used gpu for the training? And how long did it take you to complete the last step of training?
Thanks.
